#Data reading and Preprocessing

*Download and convert dataset format *
we downloaded the yelp dataset using wget modeul as we install it using %pip on local terminal to download it



1.   split data set into training and testing
2.   write data to file and process the reviews



In [ ]:
# WE DON'T RUN THIS CELL IF WE HAVE OUR DATA FILE READY (UNCOMMENT AND RUN IF YOU NEED TO RECREATE THE DATA ..BUT DOWNLOAD ALL 'yelp dataset' first )
"""
##Pre-Processing 
import collections
import numpy as np
import pandas as pd
import re

raw_train_dataset_csv=r"data/yelp/raw_train.csv"
raw_test_dataset_csv=r"data/yelp/raw_test.csv"
proportion_subset_of_train=0.1
train_proportion=0.8
test_proportion=0.2
output_csv=r"data/yelp/reviews_with_splits_lite.csv"
seed=1337


train_reviews = pd.read_csv(raw_train_dataset_csv, header=None, names=['rating', 'review'])
print(train_reviews.head())

by_rating = collections.defaultdict(list)
for _, row in train_reviews.iterrows():
    by_rating[row.rating].append(row.to_dict())
    # print(row.to_dict())
    # break
    
review_subset = []

for _ , item_list in sorted(by_rating.items()):

    n_total = len(item_list)
    n_subset = int(proportion_subset_of_train * n_total)
    review_subset.extend(item_list[:n_subset])
    # print(f"at { _ } , n total ={n_total} , n subset ={n_subset} ,\n")# item list ={item_list}\n=====\n\n")
    

review_subset = pd.DataFrame(review_subset)

by_rating = collections.defaultdict(list)
for _, row in review_subset.iterrows():
    by_rating[row.rating].append(row.to_dict())
    
final_list = []
np.random.seed(seed)

for _, item_list in sorted(by_rating.items()):

    out = self.layer1()
    np.random.shuffle(item_list)
    
    n_total = len(item_list)
    n_train = int(train_proportion * n_total)
    n_test = int(test_proportion * n_total)
    
    # Give data point a split attribute
    for item in item_list[:n_train]:
        item['split'] = 'train'
  
    for item in item_list[n_train:n_train+n_test]:
        item['split'] = 'test'

    # Add to final list
    final_list.extend(item_list)


final_reviews = pd.DataFrame(final_list)
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"([.,!?])", r" \1 ", text)
    text = re.sub(r"[^a-zA-Z.,!?]+", r" ", text)
    return text
    
final_reviews.review = final_reviews.review.apply(preprocess_text)
final_reviews['rating'] = final_reviews.rating.apply({1: -1, 2: 1}.get)
final_reviews.to_csv(r"data/yelp/reviews_with_splits_lite_new.csv", index=False)

"""

   rating                                             review
0       1  Unfortunately, the frustration of being Dr. Go...
1       2  Been going to Dr. Goldberg for over 10 years. ...
2       1  I don't know what Dr. Goldberg was like before...
3       1  I'm writing this review to give you a heads up...
4       2  All the food is great here. But the best thing...


## sloution starts from here

Here we implement our own implementation for NN and SVM classifier ( please note that we interrupted the tests because we didn't have enough time )


##implement function for one hot encodeing

in the next cell we implement the get_one_hot function .it takes review raw and convert it to one hot list with size equals vocabulary size 

In [ ]:
import collections
import numpy as np
import pandas as pd
import sklearn 

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.autograd import Variable

from random import  shuffle 

DATA_PATH = r'data/yelp/reviews_with_splits_lite_new.csv'

AllData = pd.read_csv(DATA_PATH)
print(AllData.split.value_counts())
print(AllData.head())


my_vocab =[]
word2id ={}
id2word ={}


def prepare():
  """ read all reviews and add every word of all reviews to the 
  vocabulary 'word2id' and 'id2word' dictionaries """
  for review in AllData['review']:
    for word in review.split(" "):
      if word not in word2id :
        index = len(word2id)
        word2id[word]=index
        id2word[index]= word
        

def get_one_hot(review):
        """Create a collapsed one-hot vector for the review
        Args:
            review (str): the review 
        Returns:
            one_hot (np.ndarray): the collapsed one-hot encoding 
        """
        one_hot = np.zeros(len(word2id), dtype=np.float32)
        for token in review.split(" "):
                one_hot[word2id[token]] = 1
        return one_hot

def transform_df(review_df):
  one_hot=np.empty([len(review_df) , len(word2id)])
  for i in range(len(review_df)):
    one_hot[i] =(get_one_hot(review_df[i]))
  one_hot_df = pd.DataFrame()
  one_hot_df['review'] =pd.Series(one_hot)
  return one_hot_df



train    44800
test     11200
Name: split, dtype: int64
   rating                                             review  split
0      -1  terrible place to work for i just heard a stor...  train
1      -1   hours , minutes total time for an extremely s...  train
2      -1  my less than stellar review is for service . w...  train
3      -1  i m granting one star because there s no way t...  train
4      -1  the food here is mediocre at best . i went aft...  train


###Download the pretrained Glove embedding from to stanford and process the .txt file into numpy array

After downloading Glove file and proccess it . we implemented get_Glove_vec function to take the review raw and return its Glove embedding by the averageg of its words 

In [ ]:
#download Glove
# !wget http://nlp.stanford.edu/data/glove.6B.zip
# !unzip glove*.zip
gloveModel = {}
f = open('glove.6B.100d.txt', encoding='utf-8')

print("Loading Glove Model")
for line in f:
  splitLines = line.split()
  word = splitLines[0]
  wordEmbedding = np.array([float(value) for value in splitLines[1:]])
  gloveModel[word] = wordEmbedding

def get_Glove_vec(sent):
  embed = {}
  words=sent.split()
  sent_vect=(np.mean([gloveModel[word] for word in words], axis=0)).tolist()
  return Glove_vec


Loading Glove Model


in the following line we assign the data into X and Y 

In [ ]:

prepare()
dtrain = AllData[AllData['split']=='train']
dtest = AllData[AllData['split']=='test']

xtrain , ytrain = dtrain['review'] , dtrain['rating']
xtest  , ytest = dtest['review'] , dtest['rating']
xsample , ysample = xtrain[:20] , ytrain[:20]


In [ ]:
print(xtrain.shape)
try :
  print(xtrain[22400])
except:
  print("failed")

(44800,)
failed


##The SVM Part

in the following lines we implemented the SVM classifier class and the fit function to train it  then create an instance of the classifier and train it on our one hot or Glove represented dataset on both one hot embedding and Glove embedding with mini batch gradient descent

In [ ]:
##SVM implementation
class Svm_classifier(nn.Module):
  """
  We consider the SVM as a onle layer perceptron with vector W for weights and scalar b 
  """
  def __init__(self, n_features = len(word2id)):
    super().__init__()
    print(n_features)
    self.mod_par = nn.Linear(n_features , 1)
  def forward(self ,x):
    return self.mod_par(x)


def fitsvm (model , X_train , Y_train  , embedding, batch_size=10 , epochs=1 , learning_rate =0.01 , verbose =True):

    """
    this function takes The training X and Y and fits the svm 
    to the data using the gradiant decent and the loss of the svm 
   """

    optimizer = optim.SGD(model.parameters(), lr=learning_rate)
    model.train()
    datasize = X_train.shape[0]-1
    for epoch in range(epochs):
      
      indexes = [i for i in range(len(X_train))]
      # shuffle(indexes)
      sum_loss = 0  
      for start in range(0 , datasize , batch_size):
          if start %500 ==0 :
              print(f"I am on test number {start}")
          xreview =[]
          yrating =[]
          ids = indexes[start : start+ batch_size]
          for id in ids:
              # print(id , X_train[id])
            try :
              xreview.append(get_one_hot(X_train[id]))
              yrating.append([Y_train[id]])
            except :
              continue 

          # x = [embedding(xr) for xr in xreview]
          x= torch.tensor(xreview)
          y= torch.tensor(yrating)
          
          
          if verbose :
            print(x)
            print(y)
            
          # break

          x = Variable(x)  
          y = Variable(y)
          optimizer.zero_grad() 
          yhat = model(x)  
          if verbose :
            print(yhat)
            verbose = False 
          loss = torch.mean(torch.clamp(1 - yhat * y, min=0))
          loss.backward()
          optimizer.step()
          sum_loss+=loss.data.cpu().numpy()
      print("Epoch {}, Loss: {}".format(epoch, sum_loss))
    return model

onehot_svm = Svm_classifier()
SVM_OH =fitsvm(onehot_svm , xtrain , ytrain , get_one_hot )
glove_svm =Svm_classifier(100)
SVM_GLOVE =fitsvm(glove_svm , xtrain , ytrain , get_Glove_vec )

61849
I am on test number 0
tensor([[1., 1., 1.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.]])
tensor([[-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1]])
tensor([[ 0.0093],
        [-0.0017],
        [-0.0010],
        [ 0.0055],
        [-0.0077],
        [ 0.0225],
        [ 0.0060],
        [ 0.0136],
        [-0.0120],
        [ 0.0074]], grad_fn=<AddmmBackward>)
I am on test number 500
I am on test number 1000
I am on test number 1500
I am on test number 2000
I am on test number 2500
I am on test number 3000
I am on test number 3500
I am on test number 4000


KeyboardInterrupt: ignored

## NN algorithm 

this is NN classifier implementation as NN_Review_classifier and its fit function to do training on our one hot or Glove represented dataset on both one hot embedding and Glove embedding with mini batch gradient descent

In [ ]:
class NN_Review_classifier(nn.Module):

  def __init__(self, n_features = len(word2id)):
    super().__init__()
    print(n_features)
    self.N1 =1024
    self.N2 =512
    self.layer1 = nn.Linear(n_features , N1)
    self.layer2 = nn.Linear(self.N1, self.N2)
    self.layer3 = nn.Linear(self.N2 , 1)


  def forward(self ,x):
    out = self.layer1(x)
    out = self.layer2(out)
    out = self.layer3(out)
    return out


def fit_NN (modelx , X_train , Y_train  , embedding, batch_size=10 , epochs=1 , learning_rate =0.01 , verbose =True):

    """
    this function takes The training X and Y and fits the NN 
    to the data using the gradiant decent and the loss of the NN 
    
   """

    optimizer = optim.SGD(modelx.parameters(), lr=learning_rate)
    
    modelx.train()
    loss_func = nn.BCEWithLogitsLoss()
    datasize = X_train.shape[0]
    for epoch in range(epochs):
      
      indexes = [i for i in range(len(X_train))]
      # shuffle(indexes)
      sum_loss = 0  
      for start in range(0 , datasize , batch_size):
          xreview =[]
          yrating =[]
          ids = indexes[start : start+ batch_size]
          for id in ids:
              # print(id , X_train[id])
              xreview.append(embedding(X_train[id]))
              yrating.append([Y_train[id]])

          # x = [embedding(xr) for xr in xreview]
          x= torch.tensor(xreview)
          y= torch.tensor(yrating)
          
          
          if verbose :
            print(x)
            print(y)
            
          # break

          x = Variable(x)  
          y = Variable(y)
          optimizer.zero_grad() 
          yhat = modelx(x)  
          if verbose :
            print(yhat)
            verbose = False 
          loss = loss_func(yhat, y.float())
          loss.backward()
          optimizer.step()
          sum_loss+=loss.data.cpu().numpy()
          if start %500 ==0 :
            print(f"I am on test number {start}")
      print("Epoch {}, Loss: {}".format(epoch, sum_loss))
    return model

model = NN_Review_classifier(len(word2id))
NN_OH =fit_NN(model , xtrain , ytrain , get_one_hot )
madel2=NN_Review_classifier(n_features=100)
NN_GLOVE =fit_NN(model2 , xtrain , ytrain , get_Glove_vec )

61849
tensor([[1., 1., 1.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.]])
tensor([[-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1]])
tensor([[ 0.0086],
        [-0.0053],
        [ 0.0205],
        [ 0.0219],
        [ 0.0363],
        [ 0.0356],
        [-0.0099],
        [-0.0014],
        [ 0.0053],
        [ 0.0058]], grad_fn=<AddmmBackward>)
I am on test number 0
I am on test number 500
I am on test number 1000
I am on test number 1500
I am on test number 2000
I am on test number 2500
I am on test number 3000
I am on test number 3500
I am on test number 4000
I am on test number 4500


KeyboardInterrupt: ignored